name: Force Sync Fork, Build and Push Docker Image

on:
  schedule:
    - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  sync-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/nzo66/mediaflow-proxy.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Force sync fork from upstream, preserve workflow and launcher.py
        run: |
          # Salva launcher.py se esiste
          if [ -f launcher.py ]; then
            cp launcher.py /tmp/launcher.py
          fi
          
          # Salva workflow prima del reset
          cp .github/workflows/forkanddockerhub.yml /tmp/forkanddockerhub.yml
          cp .github/workflows/buildexe.yml /tmp/buildexe.yml
          
          # Reset hard alla upstream/main
          git reset --hard upstream/main
          
          # Ripristina workflow
          mkdir -p .github/workflows
          mv /tmp/forkanddockerhub.yml .github/workflows/forkanddockerhub.yml
          mv /tmp/buildexe.yml .github/workflows/buildexe.yml
          git add .github/workflows/forkanddockerhub.yml
          git add .github/workflows/buildexe.yml
          
          # Ripristina launcher.py se era presente
          if [ -f /tmp/launcher.py ]; then
            mv /tmp/launcher.py launcher.py
            git add launcher.py
          fi
          
          # Commit e push forzato
          git commit -m "Restore workflow and launcher.py after forced sync" || echo "No changes to commit"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: qwertyuiop8899/mediaflow-proxy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
